name: Close Pull Request   

on:
  pull_request:
    types: [ closed ]

env: 
  DEV_RG_NAME: "RG-Dev-TailwindTraders-${{ github.event.pull_request.number }}"

jobs:
  deleteAzureResourceGroup:
    runs-on: ubuntu-latest
     
    environment:
      name: Dev
      
    steps:

    # log into Azure
    - name: "Login via Azure CLI"
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # delete resource group
    - name: Delete resource group
      uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          if $(az group exists --name ${{ env.DEV_RG_NAME }}) ; then
            echo "Deleting Azure resource group..."
            az group delete --name ${{ env.DEV_RG_NAME }} -y
            echo "Azure resource group deleted"
          else            
            echo "Azure resource group doesn't exist, skipping deletion"
          fi

  mergeJob: 
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: deleteAzureResourceGroup
    steps:
    - run: |
        echo PR#${{ github.event.pull_request.merged }} has been merged

