name: Developer Environment Workflow

on:

  workflow_dispatch:
    
  pull_request:
    branches:
      - main 
      - dev
          
env:

  # The name of the resource group to be created.
  DEV_RG_NAME: "RG-Dev-TailwindTraders"

  # The location to store the meta data for the deployment.
  DEV_LOCATION: "westeurope"

  # The name of the WebApp
  DEV_WEBAPP_NAME: "DEV-TailwindTraders-ADO40"

jobs:
  buildImage:
    name: build provider image
    runs-on: ubuntu-latest
    steps:

    # checkout branch
    - name: checkout main branch
      uses: actions/checkout@v2

    # log into Azure
    - name: "Login via Azure CLI"
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: "docker login"
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.DOCKER_LOGIN_SERVER }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_LOGIN_SERVER }}/tailwindtraders-ado40:dev
        context: ./TailwindTraders.Website/Source/Tailwind.Traders.Web/

   
  deploy_container:
    # Build Docker Image and push to Azure Container Registry
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Create and Deploy Container to Azure
    needs: buildImage

    environment:
      name: Dev
      url: "https://bing.com"

    steps:
    - name: Deploy infrastructure
      id: azure-deployment
      shell: pwsh
      run: |
        $deployment = $(az deployment sub create --name ${{ env.DEV_RG_NAME }} `
          --location ${{ env.DEV_LOCATION }} `
          --template-file ./main.bicep `
          --parameters location=${{ env.DEV_LOCATION }} `
          --parameters rgName=${{ env.DEV_RG_NAME }} `
          --parameters webAppName=${{ env.DEV_WEBAPP_NAME}} `
          --parameters dockerRegistryHost=${{ secrets.DOCKER_LOGIN_SERVER }} `
          --parameters dockerRegistryServerUsername=${{ secrets.DOCKER_USERNAME }} `
          --parameters dockerRegistryServerPassword=${{ secrets.DOCKER_PASSWORD }} `
          --parameters dockerImage=tailwindtraders-ado40:dev `
          --output json) | ConvertFrom-Json
      working-directory: ./TailwindTraders.Website/Deploy/IaC
    
 


