name: Developer Environment Workflow

on:
  push:
    branches: 
      - main 
  pull_request:
    branches:
      - main 
      - dev
          
env:

  # The name of the resource group to be created.
  DEV_RG_NAME: "RG-Dev-TailwindTraders"

  # The location to store the meta data for the deployment.
  DEV_LOCATION: "westeurope"

  # The name of the WebApp
  DEV_WEBAPP_NAME: "DEV-TailwindTraders-ADO40"

  # Declaring the version of .NET to be used
  DOTNET_VERSION: 5.x

  # Declaring the version of Node to be used
  NODE_VERSION: 10.x

jobs:
  buildTest:
    name: build provider image
    runs-on: ubuntu-latest
    steps:

    # checkout code
    - name: checkout branch
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
   
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies in app
      run: dotnet restore ./TailwindTraders.Website/Source/*.sln

    - name: Build, test and publish with dotnet
      working-directory: TailwindTraders.Website/Source/Tailwind.Traders.Web
      run: |
        dotnet build --configuration Release --no-restore
        dotnet test --no-restore --verbosity normal
        dotnet publish ./Tailwind.Traders.Web.csproj -c Release -o publish  
    # TODO  - Build and test code

  buildImage:
    name: Buid and Push Docker Image
    runs-on: ubuntu-latest
    needs: buildTest

    steps:

    # log into Azure
    - name: "Login via Azure CLI"
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # authenticate into Docker
    - name: "docker login"
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.DOCKER_LOGIN_SERVER }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push Docker image  
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_LOGIN_SERVER }}/tailwindtraders-ado40:${{ github.sha }}
        context: ./TailwindTraders.Website/Source/Tailwind.Traders.Web/

   
  deploy_container:
        
    runs-on: ubuntu-latest
    name: Create and Deploy Container to Azure
    needs: buildImage

    # declare GitHub Environment
    environment:
      name: Dev
      url: "https://${{ env.DEV_WEBAPP_NAME}}.azurewebsites.net" #TODO - Display URL

    steps:
    # checkout code
    - name: checkout main branch
      uses: actions/checkout@v2
    
    # log into Azure
    - name: "Login via Azure CLI"
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # deploy infrastructure with Azure Bicep - push Docker Image to WebApp
    - name: Deploy infrastructure
      id: azure-deployment
      shell: pwsh
      run: |
        $deployment = $(az deployment sub create --name ${{ env.DEV_RG_NAME }} `
          --location ${{ env.DEV_LOCATION }} `
          --template-file ./main.bicep `
          --parameters location=${{ env.DEV_LOCATION }} `
          --parameters rgName=${{ env.DEV_RG_NAME }} `
          --parameters webAppName=${{ env.DEV_WEBAPP_NAME}} `
          --parameters dockerRegistryHost=${{ secrets.DOCKER_LOGIN_SERVER }} `
          --parameters dockerRegistryServerUsername=${{ secrets.DOCKER_USERNAME }} `
          --parameters dockerRegistryServerPassword=${{ secrets.DOCKER_PASSWORD }} `
          --parameters dockerImage=tailwindtraders-ado40:dev `
          --output json) | ConvertFrom-Json
      working-directory: ./TailwindTraders.Website/Deploy/IaC
    
    # TODO: Az CLI Deploy Container Task


 


