name: WebApp Workflow - Containerized

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      CI: ""

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2

    # Login to Azure
    - name: Login via Azure CLI
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS}}

    # Calls Azure Keyvault to fetch secrets
    - name: Azure KeyVault 
      uses: Azure/get-Keyvault-secrets@v1.0
      with: 
        keyvault: ${{ secrets.KEYVAULT_DEMO }}
        secrets: 'DockerPassword'
      id: kvSecretAction
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    # Login to Azure Container Registry
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        login-server: ${{ secrets.DOCKER_LOGIN_SERVER }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build Docker image and push to Azure Container Registry
    - run: |
        cd TailwindTraders.Website/Source/Tailwind.Traders.Web
        docker build -t ${{ secrets.DOCKER_LOGIN_SERVER }}/tailwindtraders-ado40:${{ github.sha }} -t ${{ secrets.DOCKER_LOGIN_SERVER }}/tailwindtraders-ado40:latest .
        docker push ${{ secrets.DOCKER_LOGIN_SERVER }}/tailwindtraders-ado40:latest
        docker push ${{ secrets.DOCKER_LOGIN_SERVER }}/tailwindtraders-ado40:${{ github.sha }}
        cd ..