name: .NET Core

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04
    env:
      CI: ""

    steps:
    - uses: actions/checkout@v2
   
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x
   
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
   
    - name: Install dependencies
      run: dotnet restore ./TailwindTraders.Website/Source/*.sln
   
    - name: Build
      run: dotnet build ./TailwindTraders.Website/Source/*.sln --configuration Release --no-restore
   
    - name: Test
      run: dotnet test ./TailwindTraders.Website/Source/*.sln --no-restore --verbosity normal
    
    - name: Publish
      run: dotnet publish ./TailwindTraders.Website/Source/Tailwind.Traders.Web/Tailwind.Traders.Web.csproj -c Release -o './production'

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: drop
        path: "./production"

  deploy:
    runs-on: ubuntu-18.04
    needs: build
    environment: Production

    steps:

    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: drop
        path: "./production"

    - name: Deploy to Website
      uses: azure/webapps-deploy@v2
      with:
        app-name: TailwindTraders-Production
        publish-profile: ${{ secrets.PUBLISH_PROFILE_PROD }}
        package: "./production"