name: WebApp Workflow

on:
  push:
    branches: [ main ]

env:
  # Declaring the version of .NET to be used
  DOTNET_VERSION: 5.x

  # Declaring the version of Node to be used
  NODE_VERSION: 10.x

jobs:
  buildImage:
    name: build provider image
    runs-on: ubuntu-latest
    env:
      CI: ""

    steps:

    - name: Checkout main branch
      uses: actions/checkout@v2
   
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
   
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
   
    - name: Install dependencies in app
      run: dotnet restore ./TailwindTraders.Website/Source/*.sln
   
    - name: Build dotnet
      run: dotnet build ./TailwindTraders.Website/Source/*.sln --configuration Release --no-restore
   
    - name: Test dotnet
      run: dotnet test ./TailwindTraders.Website/Source/*.sln --no-restore --verbosity normal
    
 